### ISSUE TITLE
SEO Checklist for Each Page

### ISSUE THREAD

**Issue by joshuapowell** [joshuapowell/www.joshuapowell.io#14]
## MetaData
- [ ] Title Tag
- [ ] Meta Description
- [ ] Canonical Link
- [ ] Open Graph Title
- [ ] Open Graph Description
- [ ] Open Graph Image
- [ ] Open Graph URL
- [ ] Twitter Title
- [ ] Twitter Description
- [ ] Twitter Image
- [ ] Twitter URL
- [ ] Pinterest Rich Pins

## Content
- [ ] Heading 1
- [ ] Heading 2
- [ ] Heading 3
- [ ] Heading 4
- [ ] Heading 5

## Keyword Density Check

**Comment by joshuapowell** [comment]
Stale Issue.
